# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Comment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1936, 1038)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 1921, 941))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_shopid = QtWidgets.QLabel(self.centralwidget)
        self.label_shopid.setGeometry(QtCore.QRect(11, 11, 99, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_shopid.setFont(font)
        self.label_shopid.setObjectName("label_shopid")
        self.label_itemname = QtWidgets.QLabel(self.centralwidget)
        self.label_itemname.setGeometry(QtCore.QRect(116, 11, 841, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_itemname.setFont(font)
        self.label_itemname.setObjectName("label_itemname")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1936, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shop"))
        self.label_shopid.setText(_translate("MainWindow", "TextLabel"))
        self.label_itemname.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
