# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_comment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(1936, 1038)
        self.centralwidget = QtWidgets.QWidget(SubWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_commodity = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_commodity.setGeometry(QtCore.QRect(0, 70, 1921, 941))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.tableWidget_commodity.setFont(font)
        self.tableWidget_commodity.setObjectName("tableWidget_commodity")
        self.tableWidget_commodity.setColumnCount(0)
        self.tableWidget_commodity.setRowCount(0)
        self.label_shopid = QtWidgets.QLabel(self.centralwidget)
        self.label_shopid.setGeometry(QtCore.QRect(11, 11, 99, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_shopid.setFont(font)
        self.label_shopid.setObjectName("label_shopid")
        self.label_itemname = QtWidgets.QLabel(self.centralwidget)
        self.label_itemname.setGeometry(QtCore.QRect(116, 11, 841, 21))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_itemname.setFont(font)
        self.label_itemname.setObjectName("label_itemname")
        SubWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SubWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1936, 21))
        self.menubar.setObjectName("menubar")
        SubWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SubWindow)
        self.statusbar.setObjectName("statusbar")
        SubWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "Shop"))
        self.label_shopid.setText(_translate("SubWindow", "TextLabel"))
        self.label_itemname.setText(_translate("SubWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubWindow = QtWidgets.QMainWindow()
    ui = Ui_SubWindow()
    ui.setupUi(SubWindow)
    SubWindow.show()
    sys.exit(app.exec_())
